import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from './layout/SideBar'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Market Place',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full h-[150px]'></div>
        <Providers>
          <div className="root">
            <div className='side_bar'>
              <SideBar />
            </div>

            <main className='w-full '>
              {children}
            </main>

          </div>
        </Providers>
        <div className='w-full h-[350px] bg-slate-800'></div>
      </body>
    </html>
  )
}
